# Generated by Django 3.0.8 on 2020-08-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FindTrains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=100)),
                ('dest', models.CharField(max_length=100)),
                ('journey_date', models.DateField()),
                ('train_type', models.CharField(max_length=100)),
                ('night_stop', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RouteRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=100)),
                ('int_stop', models.CharField(max_length=100)),
                ('dest', models.CharField(max_length=100)),
                ('train_no_src_to_intStop', models.CharField(max_length=100)),
                ('train_no_intStop_to_dest', models.CharField(max_length=100)),
                ('prob', models.FloatField()),
            ],
        ),
    ]
