# Generated by Django 3.0.8 on 2020-08-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_auto_20200802_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='findtrains',
            old_name='night_stop',
            new_name='int_stop',
        ),
        migrations.RemoveField(
            model_name='findtrains',
            name='journey_date',
        ),
        migrations.RemoveField(
            model_name='findtrains',
            name='train_type',
        ),
        migrations.AddField(
            model_name='findtrains',
            name='train_no_intStop_to_dest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='findtrains',
            name='train_no_src_to_intStop',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='findtrains',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
