# Generated by Django 3.0.8 on 2020-08-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0003_auto_20200803_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findtrains',
            name='train_no_intStop_to_dest',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='findtrains',
            name='train_no_src_to_intStop',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='routerank',
            name='train_no',
            field=models.CharField(max_length=100),
        ),
    ]
